### ISSUE TITLE
Demo: Kroxylicious to streamline Kafka experience with Compose

### ISSUE THREAD

**Issue by gunnarmorling** [kroxylicious/kroxylicious#118]
Hey @tombentley, @k-wall, @SamBarker, et al, a potential demo and use case for Kroxylicious just came to my mind: when running Kafka in Docker Compose (i.e. its own network), the need to configure the ADVERTISED_HOST is a common stumbling block when trying to connect to that Kafka from the host itself. The reason being that the internal IP of the broker(s) in the Compose network isn't visible to clients on the host. The solution is to advertise the IP of the host and forward the Kafka port from the container. As this IP of course isn't stable, it requires some fiddling with the Compose file typically.

So I was wondering whether one could use Kroxy to simplify that: adjust metadata requests so they return the IP of the caller (which should be part of incoming requests), which should allow a client on the host to talk to Kafka inside of Compose without any further adjustments needed. Could such a filter be implemented with the current APIs already? Curious what y'all think :)

**Comment by devguyio** [comment]
I've been using Bitnami's kafka docker image with [this compose file](https://github.com/devguyio/kroxylicious/blob/docker-compose/docker-compose.yml) and I can access Kafka from my local host without the ADVERTISED_HOST being set. 

So I'm guessing that's because Bitnami solved this at the image level? i.e. using this [startup script](https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.3/debian-11/rootfs/opt/bitnami/scripts/kafka-env.sh)

**Comment by robobario** [comment]
triaged, need to review offline
