### ISSUE TITLE
API: Separate package/module/project for filter API

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#133]
See [discussion](https://github.com/kroxylicious/design/discussions/22)

We want to extract a kroxylicious-filter-api module with all the interfaces a Filter Author needs to build and configure a new filter.

As part of this we want to explore:
1. removing netty dependencies from KrpcFilterContext
2. introducing interfaces for DecodedRequestFrame, DecodedResponseFrame, DecodedFrame to keep netty out of the filter api if possible
3. Move KrpcFilter, KrpcFilterContext, other dependant interfaces and the generated per-message interfaces into a kroxylicious-filter-api module
4. Think about whether we can avoid a jackson dependency for loading the configuration, for example if we wanted a configuration class with a test constructor, it might be nice if we could use our own annotation to indicate which constructor to use rather than depend on Jackson.

**Comment by tombentley** [comment]
> 1. removing netty dependencies from KrpcFilterContext

In the discussion you called out 

>> KrpcFilterContext -> remove allocate, replace with MemoryRecordsBuilder method

+1 from me. This should be easily done in it's own PR. I think (hope) this is the only netty-ism in filter package. 

> 2 introducing interfaces for DecodedRequestFrame, DecodedResponseFrame, DecodedFrame to keep netty out of the filter api if possible

I'm still inclined to using the Kafka types (e.g. `ProduceRequestData` and `RequestHeaderData`) in the filter interfaces, rather than adding more abstractions. It just seems simpler and it gets us 90% of what we need. 

> 4. Think about whether we can avoid a jackson dependency for loading the configuration

I just don't think that's easily doable. Back when Gunnar implemented https://github.com/kroxylicious/kroxylicious/pull/69 we decided (verbally I think since I couldn't find it in the issue): 

1. To have filters expose a public constructor taking their filter class
2. One benefit of this was that filters their configuration in a type-safe way 
3. Then by using jackson we got a neat way of for a proxy user to _specify_ that configuration. 

While removing the requirement for a dependency on Jackson is desirable you can't easily do that without losing 3 (assuming you want to retain 2). 

One alternative would be to go more the Kafka route and pass configuration using something `Properties` or `Map`-like. But then there's a bunch of very tedious legwork:
* Either each filter has to validate their config (including type conversion), while results in lack of consistency and duplicated effort, 
* Or we provide some abstraction which does some of this (so that parsing from config file to Map<String, Object> or similar is done in one place), but then we need mechanisms for plugins to declare the schemas they accept.

Imho this tedious legwork adds little of value and slows us down. Better to just let people depend on jackson annotations and move on with something more interesting for now. In part that's because _maybe_ when we start thinking serious about quarkus we throw all this out in favour of compile time DI.

**Comment by robobario** [comment]
Thanks @tombentley. Another point I found while hacking on this is the dependency on a kroxy Future class in the KrpcFilterContext.

In the spike I extracted a `kroxy-futures` module for kroxy-core and the filter-api to depend on.

What do we get from this copy of vertx Futures? Could we use a java Future instead in KrpcFilterContext?

**Comment by k-wall** [comment]
Sorry, I'd like to reopen kroxylicious-api/kroxylicious-filter discussion. 

The work I'm doing on #141 generalises the `Contributor` interface and uses it for both `FilterContributor` and `AddressManagerContributor`.   `Contributor` is generic so it wouldn't make sense for it to go in `kroxylicious-filter`.  This makes the case for a `kroxylicious-api`.

#141 also brings other public API that the user (not the filter author persona) might want to implement.   This isn't filter so clearly wouldn't belong in kroxylicious-filter.  kroxylicious-address-manager-api would be overkill (well, at least premature).

Personally, I'd go for `kroxylicious-api` for the home of all public API.  If we decide to split it up further down the road, fine.

I'd also be happy with `kroxylicious-api`  `<-depens-on--` `kroxylicious-filter` (if people feel strongly that kroxylicious-filter should exist now)

**Comment by k-wall** [comment]
Any comments on my comment @tombentley @robobario @SamBarker ?

**Comment by robobario** [comment]
Yep, I'd be keen to have one public `kroxylicious-api` module for now and split later if required.

**Comment by SamBarker** [comment]
I'm persuaded of the need for a new module to encompass the entire API surface, but I'm still drawn to the idea of a separate filter module. 

`kroxylicious-api  <-depens-on-- kroxylicious-filter`

Feels like my preferred option, as it makes future changes easier. Folding `filter` into `api` seems easier than going the other way...
I'd probably lean towards an API module per persona and have `kroxylicious-api` purely an aggregator. (though I am struggling to name the other packages that would contribute)

I'm happy to live with the majority view on this.

**Comment by k-wall** [comment]
In the sprint of getting stuff moving, let's do:

kroxylicious-api  <-depends-on-- kroxylicious-filter

**Comment by robobario** [comment]
Implemented by https://github.com/kroxylicious/kroxylicious/pull/159
