### ISSUE TITLE
Record Encryption does not use new key material resulting from a rotation to encrypt newly produced records.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1339]
**Describe the bug**

The intent was that Record Encryption would, after a key rotation event in a KMS, begin to use the new key for newly produced records.  Currently the DEK doesn't expire so it takes a restart to have Record Encryption begin to use the new key.

The cache expiration controls we have around `CachingKms`  (`resolveAliasExpireAfterWrite` etc) don't help.  Even if the resolveAliasCache expires, the same KekId results, which results in the same DEK being retrieved from the `EncryptionDekCache`.

**To Reproduce**

If you run the test `io.kroxylicious.proxy.encryption.RecordEncryptionFilterIT#decryptionAfterKekRotation` against Vault and observe the bytes on the broker after the second produce, you'll observe the the key version (which happens to be serialised in a human readable way) has not been bumped.

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

On the encrypt side, we should be expiring DEKs after a configurable time period, number of encryptions, or volume of bytes encrypted.    If we had this then Record Encryption would begin to use the new KEK.

Also the integration test needs to be strengthen.  We need a way to know that the 2nd record was indeed encrypted with the key we expected.

**Comment by robobario** [comment]
Have done a little investigation just to clarify what exists.

### 1. KMS resolved KekId caching

We cache the results of the KMS resolveAlias #836. By default this is eligible to be refreshed 8 minutes after write and eligible to be expired 10 minutes after write. See the caffeine docs for [Refresh](https://github.com/ben-manes/caffeine/wiki/Refresh). The rationale here is to prevent hammering the KMS on every message intercepted by the proxy.

These values are configurable using some experimental properties as we didn't want to commit to it being part of the public config API yet.

```
    - type: RecordEncryption
      config:
        kms: VaultKmsService
        kmsConfig:
          vaultTransitEngineUrl: http://vault.vault.svc.cluster.local:8200/v1/transit
          vaultToken:
            password: myroottoken
        selector: TemplateKekSelector
        selectorConfig:
          template: "${topicName}"
        experimental:
          resolvedAliasExpireAfterWriteSeconds: 120
          resolvedAliasRefreshAfterWriteSeconds: 60
```

I had a play with `io.kroxylicious.proxy.encryption.RecordEncryptionFilterIT#decryptionAfterKekRotation` to see if reducing resolvedAliasRefreshAfterWriteSeconds would help. I think it would only affect one real case: A [manually rotated](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html#rotate-keys-manually) AWS key behind an alias. In this case there will be a delay after the user updates their alias to point at a new KeyId because we have cached the resolution.

It doesn't affect Vault because we use the Key name as KEK Id and it doesn't change through a rotation. Through the Vault API we know that the version has changed, but we don't use that information in the KEK Id. So it will keep using the cached DEK for that KEK Id.

Also I don't think it will affect [automatic/on-demand AWS rotation](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html#rotate-keys-how-it-works) as the KeyId remains the same.

Any future KMS implementation where the KekId can change for an alias would be affected by this cache too. 

### 2. DEK usage limits

DEKs can only be used to encrypt a hardcoded 5 million records. We haven't made this configurable yet. But you would get a new EDEK after that. For many low-traffic topics this might be effectively an unlimited expiry.

We maintain an encryption cache from KekId ->EDEK, there is no time based expiry involved. So an EDEK will stick around until it's 5M encryptions have been exhausted before a new EDEK is generated for a KekId.

### 3. documentation/intent

> The intent was that Record Encryption would, after a key rotation event in a KMS, begin to use the new key for newly produced records

To clarify the language from here and the docs: `When a KEK is rotated, the new key material will be applied to newly produced records.` It makes it sound like we react immediately to external rotations, or even in a timely fashion. Should we reword to make it clearer that it's an eventual transition? If we use EDEK expiry, we will be limited by that duration.

We should also doc that if they want this to be more responsive (decrease EDEK expiry), there is a cost in more EDEK creations and decryptions. ie don't drop this to 1 second or you'll smash the KMS.

What do you think would be reasonable defaults for expiry? AWS keys rotate yearly if on auto and have a limit of 10 on-demand rotations per key, so it sounds like a pretty infrequent operation in practice. 30 minutes? 1 hour?

Also I can imagine the integration tests will be a pain as cache refresh is async, if we use a refreshAfter then it will trigger an async refresh after the second hit, but we may get the current cache value while the refresh is going on. It might have to be an eventual test, hit it multiple times expecting that we see a change in EDEK within X messages.

### 4. active detection

Maybe you could implement something to make `resolveAlias` also detect if a rotation has happened and feed that back to the encryption cache to expire the EDEK.

Detecting automatic/on-demand AWS rotation looks a bit fiddly, you can find out the [next scheduled automatic rotation](https://docs.aws.amazon.com/cli/latest/reference/kms/get-key-rotation-status.html), and the last time an on-demand rotation was initiated. Then for on-demand you'd have to check [ListKeyRotations](https://docs.aws.amazon.com/kms/latest/APIReference/API_ListKeyRotations.html) to check it had finished. It's all a bit ugly.

For Vault we already receive the version number when resolving alias and could detect an increment, so that would be straightforward.

**Comment by tombentley** [comment]
An alternative (which may or may not be an improvement) would be to introspect whether the KEK has _actually_ been rotated, and only generate new DEKs if it has. One potential benefit of doing that is less churn of DEKs, and maybe a better latency distribution (maybe that's not a _real_ problem though, even at scale).

**Comment by robobario** [comment]
Here's an example of a more active detection https://github.com/kroxylicious/kroxylicious/compare/main...robobario:kroxylicious:detect-kek-rotation

This introduces a (struggling to name it) `record KekRef(K kekId, String version)` to enable `resolveAlias` to also pass back something else that identifies the version for a kekId to capture this idea that a single KekId could be backed by multiple versions of key material on the remote KMS.

We then use the KekRef as the thing we cache, so when a new version pops up, it would get a new CacheKey in the EncryptionCache and generate a new DEK (never mind that we leave an old dangling EDEK in the cache with no way to expire it currently).

For Vault this `version` could be the `latest_version` from the ReadKey response. For AWS you'd have to make further API calls to discover the `max(latestRotationTime, keyCreationTime)` and use that as the version. I've only implemented Vault's version in that branch.

A painful bit is testing. Our code is currently focused on transforming from MemoryRecords -> MemoryRecords, we do not parse to any intermediate representation. So I can't in the integration test, grab the bytes from the backing cluster and extract the EDEK  bytes with some existing code. Maybe it's better than nothing to assert that the first N bytes change (depends on the KMS how many bytes).

**Comment by k-wall** [comment]
Thanks the the investigation @robobario . I think 2 + 3 is good enough.  

- add a configurable expiryAfterWrite to the DEK encryption cache and expose it to configuration (experimental).  Also expose `maxEncryptionsPerDek` (experimental). 
- for the integration test we can dial the configuration right down.    It is hard to prove that rotation has actually worked as this level of abstraction.   If we could delete the previous key version we could show the first record becomes undecryptable, that would work.   It is possible for Vault (with [trim-key](https://developer.hashicorp.com/vault/api-docs/secret/transit#trim-key)) but it is [not supported](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html) for AWS at all.  Even if it were possible, we'd need extra configuration to have Record Encryption forget its decrypt cache.  Maybe we just satisfy ourselves with unit tests?
- update the docs to reflect the fact that key rotation is eventually consistent.

**Comment by ddaviesbrackett-dwp** [comment]
what about a way to tell a running kroxy instance to dump its DEK caches, with instructions for that to be invoked on kroxy just after completing the manual KEK rotation in the KMS (or whenever you want to run up your KMS bill, I guess)? it introduces a whole new command channel to the proxy that I think has been discussed elsewhere, to enable config changes without a restart.

**Comment by k-wall** [comment]
https://github.com/kroxylicious/kroxylicious/pull/1354 has provided configuration so that the length of time a DEK will be used is configurable, with a sane default.

@robobario we said above that the docs should be updated to reflect the factor that key rotation is eventually consistent.   I think this needs to be done before this issue is closed.   Do we document the config params too?  I might be odd not to.  WDYT?

**Comment by robobario** [comment]
> https://github.com/kroxylicious/kroxylicious/pull/1354 has provided configuration so that the length of time a DEK will be used is configurable, with a sane default.
> 
> @robobario we said above that the docs should be updated to reflect the factor that key rotation is eventually consistent.   I think this needs to be done before this issue is closed.   Do we document the config params too?  I might be odd not to.  WDYT?
> 
> Also, it does seem weird that we've now got tuning parameters for time but not for number (maxEncryptionsPerDek).  I'd be incline to give this an experiement config parameter too.

Sounds good, I wonder what we should say about experimental config? Should we give any guarantees about backwards compatibility? It's a bit risky that a user could use them, then we refactor the Filter and silently ignore the old experimental configuration.

Also, yes making the number encryptions configurable would be nice. I think you could call it part of the solution to this issue as it impacts how frequently new DEKs are created.

**Comment by SamBarker** [comment]
We say that experimental means exactly that! There are no promises that keys will remain, and if they do they will have a new prefix.

I've no problems documenting them but they have to come with a health warning and maybe an explicit time limit
