### ISSUE TITLE
Record encryption: support a FIPs-certified cipher from an alternative provider

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#1401]
from @ddaviesbrackett-dwp in slack

RecordEncryption question: Would Kroxylicious be open to changing the cipher transformation used by the Aes CipherManager from AES_256/GCM/NoPadding to AES/GCM/NoPadding to enable clients to use the FIPS-validated BouncyCastle JCE? Or adding another CipherManager that depended at compile time on bc-fips.jar? Or some other way I can assure my security folk I'm using fips-validated encryption?

**Comment by SamBarker** [comment]
@tombentley would be my go to person for asking about our "Designed for FIPS" status as we can't claim FIPS support without being actually approved. 

But my understanding is that FIPS enabledness is mostly just down to the JVM itself but maybe thats a Red Hat view. 

For reference here is the [FIPS cert](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4743) for Bouncy Castle 2.0.0 and further details are here https://www.bouncycastle.org/download/bouncy-castle-java-fips/#release-notes

**Comment by ddaviesbrackett-dwp** [comment]
We have bouncycastle almost entirely grafted onto Kroxy without code changes to Kroxy (hooray for JCE!), with the exception of hacking [the first string parameter in Aes.java](https://github.com/kroxylicious/kroxylicious/blob/47ea71a1cd224e6e0810af553bdde4a7f0ea7c37/kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/dek/Aes.java#L23) to be `AES` rather than `AES_256`, so that bouncycastle accepts it. 

I will note that we did this with bc-fips 1.0.2.4 and not the hot-off-the-presses 2.0 jar, I guess I should reconfirm with 2.0

**Comment by robobario** [comment]
Having discussed it:

One idea is to make the cipherSpecName and provider user configurable for the existing AES_256_GCM_128 CipherSpec. We see that multiple providers may offer AES_256_GCM_128 using different cipher names, and it could be a user decision which to use.

1.  We think we should also enable you to configure the provider name, so that you do not unexpectedly load ` AES/GCM/NoPadding` from the JRE.
2. We want to try to keep the guarantee that if the wire format has the `AES_256_GCM_128` id encoded in it, that what we write is `AES_256_GCM_128`. So it would be scary if the user could configure the AES_256_GCM_128 cipher name to an arbitrary algorithm. So perhaps we should make it configurable, but only allow it to be set to `AES_256/GCM/NoPadding` or `AES/GCM/NoPadding`.

We also see some risk that `AES/GCM/NoPadding` doesn't define a key length, so if the world conspires against us and the KMS returns a 128 bit key, the provider may just quietly support that. We don't have a lot of protection for this and rely on `AES_256/GCM/NoPadding` to require a 256bit key. We could make some more API changes in the KMS to describe what length key we require.

**Comment by tombentley** [comment]
I think the contracts we want are as follows:

1. That when the user asks to encrypt with AES with 256 bit key that's what they actually get.
    - This isn't something the filter itself can guarantee since we're using JCE, and the JCE API doesn't allow a way to say "get me a `Cipher` impl for AES that will support 256 bit keys". This is less of a problem now that OpenJDK supports 256 bit AES OOTB, but it's not something that's guaranteed by the Java platform (which is what we were worrying about in #1050). The platform still allows for "limited" crypto policies (`Security.setProperty("crypto.policy", "limited");`) which mean that 256 bit AES will not be available. 
2. That the user can configure other security providers using the standard mechanisms and the proxy will use them (which is what @ddaviesbrackett-dwp is asking for)

This has some implications:

- The "decryptability guarantee" comes with a caveat: That you're attempting to decrypt records on a JVM which supports both the cipher _and the key size_ that was used to encrypt them. The kroxy code can't guarantee this. It's up to the user to run it on a suitable JVM.
    - We already have `RecordEncryption#checkCipherSuite()` which is used to fail fast when ciphers aren't available, but we should add a check for the key size.
    - It's not clear that fail fast is actually the right thing to do if we support multiple `CipherManagers`. I.e. I suppose it's possible that one `CipherManager` is available and another is not available. If the user wants to use the one that is available the proxy should still start.
    - In other words what we need at start up is not fail fast, but filtering of the `CipherManagers` available from the platform (and it's configured `Providers`). 
- Currently `Kms.generateDekPair()` doesn't really require that the returned key has any particular properties (such as a specific/minimum number of bits). The KMSs we've implemented do the right thing for the CipherManagers we currently have, but the APIs are underspecified. 

So we need to:
1. Switch to using "AES" for `Aes.AES_256_GCM_128`
2. Filter the available CipherSpecs based on key size. Fail startup only if the result is empty. Validate that the chosen CipherSpec is allowed.
3. On the decryption path have a clear exception thrown if we cannot decrypt a record because the key size is not supported (even though the cipher is).
4. Check that the keys returned from the `Kms` meet the requirements of the cipher, fail if they don't.

**Comment by SamBarker** [comment]
@tombentley  does your answer mean that we don’t need to care about
> We think we should also enable you to configure the provider name, so that you do not unexpectedly load AES/GCM/NoPadding from the JRE.

from @robobario’s [comment]( https://github.com/kroxylicious/kroxylicious/issues/1401#issuecomment-2273026524)?

Its not explicit in the request but everyone would be surprised if bouncycastle was available but we used AES/GCM from the JVM and not from bouncycastle?

**Comment by tombentley** [comment]
The security policy file can be used to prefer BC over SunJCE (just for AES if necessary). It would be simpler to build on what the platform supports by default than to layer additional stuff on top of that and that seems to be sufficient for @ddaviesbrackett-dwp. When someone brings along a requirement for more configurability we can to design a solution knowing some more detailed requirements.

**Comment by robobario** [comment]
Isn't there an implicit requirement here already, they want to use a FIPs certified provider. Letting it quietly load a non-FIPs algorithm is ugly.

But from my exploration it would be a chunky refactor to try and introduce a concept of "trusted providers" for the algorithms or enable the user to explicitly choose a provider.

If we put it on the users to configure it correctly and call it sufficient, we should at least help them by spitting out some logs about where the ciphers came from during configuration.

**Comment by robobario** [comment]
> Filter the available CipherSpecs based on key size. Fail startup only if the result is empty. Validate that the chosen CipherSpec is allowed.

Do you mean filter the available CipherSpecs down to ones where the key size is supported on the current platform?

Would we try and construct each Cipher with the expected key size and mark it failed if it doesn't initialize? You also had an idea about testing the cipher with fixed inputs to see it it really is AES_256_GCM_128 which sounded like an interesting idea.

**Comment by robobario** [comment]
For `Check that the keys returned from the Kms meet the requirements of the cipher, fail if they don't.` do you mean the requirements of our CipherSpec?

**Comment by tombentley** [comment]
@robobario I'll try to push a PR tomorrow.

**Comment by ddaviesbrackett-dwp** [comment]
Thanks @tombentley - sounds like what we're asking for. 

> If we put it on the users to configure the environment correctly and call it sufficient, we should at least help them by spitting out some logs about where the ciphers came from during configuration.

this would also be helpful to increase confidence.

**Comment by robobario** [comment]
@ddaviesbrackett-dwp that fix is in main now as described by Tom (pared down a little):

1. Switch to using "AES" for Aes.AES_256_GCM_128
2. Check that the keys returned from the Kms meet the requirements of the cipher, fail if they don't.

and a one-off INFO log at startup showing which provider the Ciphers are loaded from.

0.7.0 should be released soon

**Comment by SamBarker** [comment]
Fixed by https://github.com/kroxylicious/kroxylicious/pull/1418 and https://github.com/kroxylicious/kroxylicious/pull/1424

**Comment by ddaviesbrackett-dwp** [comment]
thanks gents!
