### ISSUE TITLE
GitHub actions latency too volatile to be useful.

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious#347]
results from [1st run](https://github.com/kroxylicious/kroxylicious/commit/7311b983986a52a5621efb353cf70ba3412ff81d):

```
AVG Latency: 37.44ms
95th Latency: 274ms
99th Latency: 391ms
```

[2nd run](https://github.com/kroxylicious/kroxylicious/commit/671442a188face22b3e1e084bf28c60e93f2e997):

```
AVG Latency: 11.33ms
95th Latency: 6ms
99th Latency: 245ms
```

not sure if we can draw much conclusion since these kind of fluctuations are typical in the action

_Originally posted by @robobario in https://github.com/kroxylicious/kroxylicious/issues/343#issuecomment-1567543499_

**Comment by franvila** [comment]
Can we close this issue since we have already moved the pipeline to strimzi-ci? The results are much more stable since we have the control over the resources used for the performance tests:
![Screenshot from 2023-07-13 11-39-15](https://github.com/kroxylicious/kroxylicious/assets/57452611/9e157568-7b42-4ca1-b9d8-7916826ecf40)
