### ISSUE TITLE
Request/Response Forward Asynchronicity

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#351]
**Describe the bug**

I believe that Kroxylicious filters ought to allow a programming style where request/responses are forwarded only after some asynchronous work completes.    The ordering of requests/responses for a single connection must not be unaffected (that is another request should not be allowed to leapfrog an earlier request just because the earlier message's processing is being held up by a filter's async work). 

From an API point of view, it might look like this:

```
    @Override
    public void onRequest(ApiKeys apiKey, RequestHeaderData header, ApiMessage body, KrpcFilterContext filterContext) {

       var someFuture = someExternalActionThatReturnsFuture();
       someFuture.thenApply(r -> {
           filterContext.forwardRequest(header, body)
       });
    }
```

Internally, Kroxylicious should do this without causing a Netty thread to become blocked. 

As discovered by #271, currently that usage pattern doesn't work.

**To Reproduce**

See integration test being added by the PR.

https://github.com/kroxylicious/kroxylicious/blob/4cc5fd0c0a3f72c01de38a3632225cf1c9de80b3/integrationtests/src/test/java/io/kroxylicious/proxy/KrpcFilterIT.java#L206 

**Expected behavior**

When a filter chain opts not to completely forward a request to the upstream Kroxylicious should respond by not reading further from the downstream until the chain has been completed.  Similarly, in the opposite direction, if a filter chain opts not to  completely forward a response to the downstream, Kroxylicious must not read further from the upstream until the chain has completed. 

Kroxylicious must not allow requests or response to leap frog as that behaviour could result in changes to record ordering.

**Additional context**

**Comment by k-wall** [comment]
@robobario I haven't made much progress today. I had hoped by controlling the channel's autoread settings, I could prevent the pipeline processing until we were ready to continue.  That doesn't work because the codec optimistically decodes the whole bytebuffer and those requests get processed regardless. 

I found `setSingleDecode` and realised our decode has a bug which means it doesn't respect that request.  However, even with that fixed, something is still triggering `read`.    Even if this was to work, I don't think we'd want `setSingleDecode(true)` as there are warnings about performance.

We could add handlers that is prepared to queue requests from the downstream (and responses from the upstream) when a request is still in flight. 

However, I'm having second thoughts about the whole thing.  Maybe I'm fixating on something that's not so important. Maybe we just accept the fact that netty thread will block? WDYT?

**Comment by robobario** [comment]
I think the issue is correct, being able to support async work from the filters is useful for the likes of topic encryption. But maybe it's good enough to get started with synchronous-only and we can find a way to support async later. If we start with sync only we should add it to the filter javadoc and maybe add some code to check that the KrpcFilterContext has been called after we invoke the filter code, so we can warn users that they haven't synchronously called a method on KrpcFilterContext.

Another idea could be to make the FilterHandler do the ordering using a chain of `Future`s. The contract would be that all Filters must call a method on the KrpcFilterContext so that a future can be completed, driving the FilterHandler.

Rough example here: https://github.com/robobario/kproxy/commit/02c04b8b0384a30f2cf95b277fea41a93ee893f6

**Comment by robobario** [comment]
If we go with synchronous only for now, I wonder if we should enforce synchronous work in the Filters, rather than just have it be a convention. We could add a discard method to the KrpcFilterContext for the case where we want to drop the message. Then we could track on the Context when a method like `forwardRequest` , `discard`, `abortConnection`, `sendRequest` is called with an atomic. Then check in the FilterHandler if something completed it after the invoke and it could fail noisily if the Filter author hasn't explicitly taken some action.

**Comment by k-wall** [comment]
So on #271, we've switched to using synchronous reconciliation, at least for now.  That allows 271 to merge.

> Another idea could be to make the FilterHandler do the ordering using a chain of Futures. The contract would be that all Filters must call a method on the KrpcFilterContext so that a future can be completed, driving the FilterHandler.

I'm not getting how the future ideas stops on request (or response) overtaking another.  What am I missing?

> Then we could track on the Context when a method like forwardRequest , discard, abortConnection,

Just on the `discard` idea - would it ever make sense for kroxy to drop a kafka request?  I think it would result in an illegal state in all circumstances except publish acks=0.

**Comment by robobario** [comment]
> So on #271, we've switched to using synchronous reconciliation, at least for now. That allows 271 to merge.
> 
> > Another idea could be to make the FilterHandler do the ordering using a chain of Futures. The contract would be that all Filters must call a method on the KrpcFilterContext so that a future can be completed, driving the FilterHandler.
> 
It's an implementation of queuing. A `FilterHandler` will only process the next read when the previous read completes by calling some method on the `KrpcFilterContext`, similar with write. Perhaps it could be combined with toggling autoread. Maybe FilterAuthors would have to signal that they are deferring completion? Like a `suspend/detach` type method on `KrpcFilterContext` that would toggle autoread and instruct the FilterHandler to start queuing requests.

> Just on the `discard` idea - would it ever make sense for kroxy to drop a kafka request? I think it would result in an illegal state in all circumstances except publish acks=0.

True, better to not make it look like a supported mechanism in the API

**Comment by k-wall** [comment]
@franz1981 would you have any words of Netty wisdom to offer?  Is there a standard Netty pattern for solving this type of issue?

**Comment by franz1981** [comment]
> Perhaps it could be combined with toggling autoread

I have discarded such option in the initial implementation of the proxy because of great drawback in term of performance. Autoread force interacting the the SO and still it won't prevent a full already batchy read to suspend really. 
I am in PTO today, but probably what you need is a non blocking semaphore primitive or just make uses of what mutiny-like/RxJava promote to perform configurable level of non blocking backpressure. But still, if the unit of work is just one, and it backpropagate till the channel to drain, the risk is a great performance penalty. 
I will look at this next week again, with a non-PTO brain, I promise :P

**Comment by robobario** [comment]
Might be worth retro-fitting/updating this Issue with some of the ideas that are evolving as we try to implement this:

The goal is to enable users to do some amount of async work in a non-netty Thread, without breaking the contract that messages from the client will be delivered to the upstream broker in order, and responses to the client will be sent in order.

### Option 1 (where we are heading): make the Filter APIs asynchronous

``` java
class PrefixingFilter implements RequestFilter {
    @Override
    public CompletionStage<RequestFilterResult> onRequest(ApiKeys apiKey,
                                                          RequestHeaderData header,
                                                          ApiMessage body,
                                                          KrpcFilterContext filterContext) {
       var someFuture = someExternalActionThatReturnsFuture();
       return someFuture.thenApply(r -> {
           return filterContext.forwardRequest(header, body);
       });
    }
}
```

Instead of instructing the `KrpcFilterContext` to forward, we use the `KrpcFilterContext` to obtain a `CompletionStage<RequestFilterResult>` and return that from our `Filter` methods.

A benefit of doing it this way is that it can be composed with the existing async APIs available on `KrpcFilterContext`, namely the `sendRequest` completion stage. We can chain off the `CompletionStage<ApiMessage>` and return the resulting stage if we want to wait for the "additional request" to complete before forwarding. If we do not wish to delay forwarding we can return a completed forward stage immediately. So we have consistency.

Another benefit is that this API (requiring a single return) pushes the Filter Author to make one decision about what will eventually be done in reaction to the message. With the existing `KrpcFIlterContext` there is ambiguity about how it can be used. Can it's methods be called multiple times, when can I call `closeConnection`, can I call any of the methods from another thread, is it legal to call no methods? With a Result object and Builder we can organise it so that Authors can see more easily which actions are permitted in a given context. We can build a safer API this way.

### Option 2 (original idea): allow users to call the existing methods on the `KrpcFilterContext` asynchronously

```
    @Override
    public void onRequest(ApiKeys apiKey, RequestHeaderData header, ApiMessage body, KrpcFilterContext filterContext) {

       var someFuture = someExternalActionThatReturnsFuture();
       someFuture.thenApply(r -> {
           filterContext.forwardRequest(header, body)
       });
    }
```

This is quite similar to returning a `CompletionStage`, in that the `KrpcFilterContext` behaves as a Promise.  Users can complete it with the existing methods either immediately or asynchronously. However as discussed above there are far more ambiguities.

A user can omit calling any methods on the context and the promise will never complete (I think this is a different class of problem from a user deciding to do some async work). In option 1 they are herded towards making a decision (and we can fail fast if they do something funky like return an empty future or null). To discriminate between user error and awaiting some future result using this api, we could introduce a method like `KrpcFilterContext#defer()` and require that they call it if going async, which is error prone.

A user can call `forwardRequest` only while handling a request, but `forwardResponse` can be used to short-circuit during request handling, or to forward during response handling. Calling `forwardRequest` at the wrong time is an error. By introducing the Result classes in option 1 we can remove this class of errors because they cannot construct a `ResponseFilterResult` that forwards a request. We can also more smoothly add meaningful naming like `shortcircuitResponse` in option 1, where here we have opted to re-use the existing method to keep the API smaller.

Users can also call the forward methods more than once, which they cannot in option 1. They can do odd things like `closeConnection` then try to `forward`. With the option 1 API we can control these interactions so users can do things like `forward response then close connection` but not the other way around.

**Comment by k-wall** [comment]
#494 addressed only the API.  Follow up work will resolve the defect that causes messages to go out of order.
