### ISSUE TITLE
Refer to sample filter project in the docs.

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#418]
**Is your feature request related to a problem? Please describe.**
Potential Filter Authors could use a quick way into the code when they stumble on our github/site

**Describe the solution you'd like**
1. A link from the front github README.md to the sample filter project README
2. A link from the website docs to the sample filter project README (could be on the website frontpage https://kroxylicious.io/ or at https://kroxylicious.io/kroxylicious)

**Comment by robobario** [comment]
FYI: the [front website](https://kroxylicious.io/) repo is [this one](https://github.com/kroxylicious/kroxylicious.github.io), and the https://kroxylicious.io/kroxylicious page is generated from [here](https://github.com/kroxylicious/kroxylicious/tree/main/docs)

**Comment by gracegrimwood** [comment]
> 2. A link from the website docs to the sample filter project README (could be on the website frontpage https://kroxylicious.io/ or at https://kroxylicious.io/kroxylicious)

How about in the docs under [Custom Filters > Protocol Filters > An example protocol filter](https://kroxylicious.io/kroxylicious/#_protocol_filters)? Or perhaps we could have a new "Sample Filters" section under Custom Filters (instead of/in addition to the two empty sections for example filters), with a view to maybe having a sample net filter in kroxylicious-sample in the future too?
