### ISSUE TITLE
Out-of-band requests have upstream Request filters applied, but not upstream Response filters.

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#445]
> I confirmed it [experimentally](https://github.com/kroxylicious/kroxylicious/compare/main...robobario:kproxy:intercept-out-of-band). Will make an issue to find the right solution separately.

_Originally posted by @robobario in https://github.com/kroxylicious/kroxylicious/pull/437#discussion_r1259145995_
 
Currently when you send an out-of-band request to the Cluster from a Filter, upstream filters are applied to the request. But when handling the response other user filters are not invoked. The FilterHandler[ forwards it on ](https://github.com/kroxylicious/kroxylicious/blob/4be5632203f131e26c25a3db38f5dd3a54aa5bbc/kroxylicious/src/main/java/io/kroxylicious/proxy/internal/FilterHandler.java#L92)until it gets to the FilterHandler for the recipient/sender Filter, at which point it completes the future.

**Comment by robobario** [comment]
What would be a good default behaviour?

1. Apply upstream filters to request and response
2. Apply no upstream filters to request or response

Possibly we could make it a parameter of `sendRequest` like `sendRequst(boolean applyUpstreamFilters)` to let users decide if they want to send a request and get the response without any intervening manipulation by upstream filters.

**Comment by k-wall** [comment]
I think the Javadoc for io.kroxylicious.proxy.filter.KrpcFilterContext#sendRequest already captures the semantics right.  Out of band requests go through the filters between `filter[this+1]..filter[n]`, and the response traverse `filter[n]..filter[this-1]`.  I don't think we should have `applyUpstreamFilters`  configurability.   I say this because I think it would detrimentally affect composability of filters/make the system harder to reason about.  For example, If I insert 'MandatoryLegalAuditFilter' at the end of the my chain, I want to be able to trust the system to pass every request that goes towards the broker through it.

There might be a use-case for allowing a filter to determine that the request/response it is seeing is as a result of a OOB request so it could take alternative action, but i think we should wait until we see that use-case before we action it.

**Comment by SamBarker** [comment]
+1 to everything @k-wall [said](https://github.com/kroxylicious/kroxylicious/issues/445#issuecomment-1630933599).

**Comment by robobario** [comment]
:+1: cool, I'll get a PR together
