### ISSUE TITLE
Envelope Encryption: Support another Cipher

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#815]
> I'm keen that _eventually_ (post 0.5.0 timeframe) we add support for at least one other cipher. XChaCha20Poly1305 is one candidate, though it's not available in JCE currently.

_Originally posted by @tombentley in https://github.com/kroxylicious/kroxylicious/pull/798#discussion_r1419792864_

**Comment by tombentley** [comment]
I'm going to close this. We didn't add support for `XChaCha20_Poly1305`, since there wasn't a JCE provider for it within easy reach (i.e. it's [not in the JDK](https://bugs.openjdk.org/browse/JDK-8256529) yet and it's [not yet in BouncyCastle](https://github.com/bcgit/bc-java/issues/631) either). We did add support for `ChaCha20_Poly1305`, which means users have _a_ choice, and we've got the machinery in place to add support other (symmetric) ciphers relatively easily, without impacting the serialization.
