### ISSUE TITLE
Add system test for prometheus metrics

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#918]
Kroxylicious has built in support for a prometheus endpoint and our filters are using micrometer to capture useful metrics. We should system test that this endpoint functions in our production artefacts to have confidence users can access this data.

**Comment by k-wall** [comment]
We discussed on today's triage call that we want to understand if metrics are functional end to end for 0.5.0.   I'll bring this card into scope.

**Comment by k-wall** [comment]
So I think the aim of the system test is to show that kroxylicious integrates with Prometheus.   We want to show that for both Kubernetes and OpenShift.  On OpenShift the monitoring stack is already available - it is part of the  "Monitoring for user-defined projects"

**Comment by k-wall** [comment]
@franvila and I chatted about this in another place.  He favours the approach that Strimzi take https://github.com/strimzi/strimzi-kafka-operator/blob/8249e8d42d109769919294f55ea3d689773bfd88/systemtest/src/test/java/io/strimzi/systemtest/metrics/MetricsST.java#L147 where a scraper pod is used to make metric observations, rather than pulling in the whole of Prometheus into the test.  I'm happy with that.
