### ISSUE TITLE
System tests PR runs don't use the an image built from the PR

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#961]
As a developer, I can run the system tests from PR by requesting it from the strimzi-ci robot.   That's running the system tests from the PR branch but not the code.  The reason is that the system test run is picking up the container image from main.

```quay.io/kroxylicious/kroxylicious:0.5.0-SNAPSHOT```

Perhaps our automation should:

* Build a PR candidate image somewhere.
* Invoke the system test run with the candidate image.

We'd want to think through any new attack vectors (if any) before making a change.

**Comment by k-wall** [comment]
@franvila low priority, but what are your thoughts?

**Comment by franvila** [comment]
Sorry Keith but that's not the case. We are compiling and uploading a new image to quay with the code generated in the PR. 
The thing here is that we are overwriting the image located at `quay.io/kroxylicious/kroxylicious:0.5.0-SNAPSHOT` every time, that's why we don't allow parallel runs of the PR jenkins jobs. The version of the image generated will depend on the current project version.

**Comment by k-wall** [comment]
Oh..  that violates least surprise.   You wouldn't expect 0.5.0-SNAPSHOT to contain a PR build.

If we want the PR images on the public repo (maybe that helps), then they should be tagged with the commit sha, so we understand which PR they related to.

We should set the [tag-expiration label](https://access.redhat.com/documentation/ja-jp/red_hat_quay/3.3/html/use_red_hat_quay/tag-expiration) on the image (~6h)?

You can pass additional label from the `docker build --label "name=value` so it should be easy to adapt the script.
